export { ReactComponent as ArrowRight } from './arrow-right.svg'
export { ReactComponent as Pause } from './pause.svg'
export { ReactComponent as Play } from './play.svg'
export { ReactComponent as Reset } from './reset.svg'
export { ReactComponent as Settings } from './settings.svg'
export { ReactComponent as Stop } from './stop.svg'
